### PR TITLE
Assets manager UI

### PR DESCRIPTION
**Pull request by vdraganic21**
Implemented UI for Assets page. Consists of header, add and delete buttons, search field, sort menu and assets list.

There is currently no background logic implemented.

### CODE REVIEW

**Comment by lrakic20** [comment]
Missing some icons, rest looks good, like the prototype.

**Comment by vdraganic21** [comment]
> Missing some icons, rest looks good, like the prototype.

I had trouble implementing the icons. It's not a urgent matter, we can implement them down the line.

**Review by lrakic20 — APPROVED** [review]
merge approved, looks good, icons will be added later

**Comment by mmathis21** [comment]
Works fine, responsive, ready to merge

**Review by mmathis21 — APPROVED** [review]
Works good, responsive, ready to merge

**Pull request merged**
