### PR TITLE
Changed version of font awesome icons in main. Added bottom right control buttons.

### PR DESCRIPTION
**Pull request by aslavicek21**
Added buttons "refresh", "zoom in" and "zoom out" visually.

### CODE REVIEW

**Comment by vdraganic21** [comment]
Good job, lgtm 🔥

**Comment by mmathis21** [comment]
Good work, everything is fine.

**Review by mmathis21 — APPROVED** [review]
Good work, everything is fine.

**Review by vdraganic21 — APPROVED** [review]
Good job, lgtm 🔥

**Pull request merged**
